### ISSUE TITLE
Cannot resolve module 'react/lib/invariant'

### ISSUE THREAD

**Issue by DoubleU23** [pieterv/react-googlemaps#37]
```
Module not found: Error: Cannot resolve module 'react/lib/invariant' in /var/www/htdocs/projects/SSS/web/node_modules/react-googlemaps/src/ui
```

FYI: I'm on React@0.14.0 and can't downgrade because of other dependecies...

**Comment by TGMorais** [comment]
+1

**Comment by vasco** [comment]
+1

**Comment by factoryhr** [comment]
+1

**Comment by sysatom** [comment]
+1

**Comment by kevinfu2** [comment]
my problem solved by run command   `npm install invariant`
npm version  2.14

**Comment by dmitriid** [comment]
The problem is still there. Both for React v0.14 and v0.15

`npm install invariant` doesn't help

**Comment by DoubleU23** [comment]
This ticket is still open after ~4 years!
so im closing it...
